# Generated by Django 4.2.1 on 2023-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
